# Generated by Django 4.0.4 on 2022-05-09 15:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=30)),
                ('valor', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='cuentas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('fecha_de_creado', models.DateField()),
                ('colaboradores', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('pagos', models.ManyToManyField(to='split.pagos')),
            ],
        ),
    ]
