# Generated by Django 4.0.4 on 2022-05-09 20:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('valor', models.IntegerField()),
                ('creador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cuentas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('fecha_de_creado', models.DateField(default=django.utils.timezone.now)),
                ('colaboradores', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('pagos', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='split.pagos')),
            ],
        ),
    ]
