# Generated by Django 4.0.4 on 2022-05-09 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('split', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuentas',
            name='pagos',
        ),
        migrations.AddField(
            model_name='cuentas',
            name='pagos',
            field=models.ManyToManyField(to='split.pagos'),
        ),
    ]
