# Generated by Django 4.0.4 on 2022-05-09 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('split', '0002_pagos_creador_alter_cuentas_fecha_de_creado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagos',
            name='creador',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
