# Generated by Django 4.0.4 on 2022-05-12 21:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('split', '0005_rename_porfile_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagos',
            name='creador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to=settings.AUTH_USER_MODEL),
        ),
    ]
