# Generated by Django 4.0.4 on 2022-05-12 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('split', '0006_alter_pagos_creador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagos',
            name='cuentas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuentas', to='split.cuentas'),
        ),
    ]
