# Generated by Django 4.0.4 on 2022-05-13 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('split', '0008_payment_pocket_remove_pagos_creador_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='pockets',
            new_name='pocket',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='name',
        ),
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('value', models.IntegerField()),
                ('pocket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='split.pocket')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='charge', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
