# Generated by Django 4.0.4 on 2022-05-16 23:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('split', '0010_pocket_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='charge',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='payment',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='pocket',
            name='categories',
            field=models.CharField(choices=[('trip', 'trip'), ('home', 'home'), ('couple', 'couple'), ('friends', 'friends'), ('other', 'other')], max_length=255, null=True),
        ),
    ]
