# Generated by Django 4.0.4 on 2022-05-17 02:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('split', '0011_charge_date_payment_date_pocket_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pocket',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
