# Generated by Django 4.0.4 on 2022-05-17 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('split', '0012_alter_pocket_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pocket',
            name='name',
            field=models.CharField(max_length=15),
        ),
    ]
