# Generated by Django 4.0.4 on 2022-05-17 16:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('split', '0013_alter_pocket_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
