# Generated by Django 4.0.4 on 2022-05-18 14:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('split', '0014_alter_charge_date_alter_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='charge',
            name='payment_methods',
            field=models.CharField(choices=[('solo', 'solo'), ('equally', 'equally')], max_length=255, null=True),
        ),
        migrations.RemoveField(
            model_name='charge',
            name='user',
        ),
        migrations.AddField(
            model_name='charge',
            name='user',
            field=models.ManyToManyField(related_name='charge', to=settings.AUTH_USER_MODEL),
        ),
    ]
