# Generated by Django 4.0.4 on 2022-05-18 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('split', '0015_charge_payment_methods_remove_charge_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charge',
            name='payment_methods',
        ),
    ]
